import Navigation from "./Navigation";

const repo = "https://github.com/UnrealAnkit/pocketcodeapk";
const working = [["Remote terminal", "Real PTY, multiple tabs, ANSI color"], ["File browser", "Tree navigation and remote file access"], ["Git controls", "Status, diff, stage, commit, push, branches"], ["Agent monitoring & approval", "Live activity with remote responses"], ["Notifications & pairing", "Actionable notifications, multi-machine support"], ["Tunneling", "Tailscale, devtunnel, and SSH support"]];
const future = [["Polished agent workflows", "More ways to supervise a running agent"], ["Better mobile editing", "Improved workflows for project changes"], ["Expanded platform support", "More ways to connect to your machine"], ["Additional integrations", "Built around real developer workflows"]];

const CTA = ({ quiet = false, children }) => <a className={`button ${quiet ? "quiet" : ""}`} href={repo} target="_blank" rel="noreferrer">{children}</a>;
const Eyebrow = ({ children }) => <div className="eyebrow">● {children}</div>;

export default function Home() {
  return <><Navigation /><main id="top">
    <section className="hero section"><Eyebrow>OPEN SOURCE REMOTE CONTROL FOR YOUR DEV ENVIRONMENT</Eyebrow><h1>Control your code editor<br /><em>from your phone.</em></h1><h3>Your terminal, files, Git, and AI agents. Anywhere.</h3><p>PocketCode gives your phone a direct window into the development environment running on your computer. Check your terminal, inspect files, review Git changes, and respond to coding agents without being tied to your desk.</p><div className="actions"><CTA>Try the Beta →</CTA><CTA quiet>◉ View on GitHub</CTA></div><div className="meta">Open source <b>•</b> MIT License <b>•</b> Android <b>•</b> VS Code</div>
      <div className="hero-demo"><div className="desktop"><header><span>● ● ●</span><b>pocketcodeapk — Visual Studio Code</b><span>⌘ P</span></header><div className="screen"><aside><small>EXPLORER</small><b>⌄ POCKETCODEAPK</b><span>⌄ &nbsp;android</span><span>⌄ &nbsp;docs</span><span>⌄ &nbsp;extension</span><strong>&nbsp;&nbsp;&nbsp;server.ts</strong><span>&nbsp;&nbsp;&nbsp;protocol.ts</span><span>⌄ &nbsp;tools</span></aside><article><div className="tabs">server.ts　 agent-detector.ts</div><pre><i>12</i> <mark>const</mark> session = <mark>await</mark> server.start(&#123;{"\n"}<i>13</i>   host: <q>&apos;127.0.0.1&apos;</q>,{"\n"}<i>14</i>   tunnel: <q>&apos;tailscale&apos;</q>,{"\n"}<i>15</i> &#125;);</pre><div className="terminal"><span className="path">~/Projects/pocketcodeapk</span> <small>main</small><br />$ npm test<br /><b>✓ PASS　60 tests passed</b><p><i /> <strong>Claude Code</strong>　 Working on extension/src/server.ts</p></div></article></div></div>
      <div className="phone"><div className="notch" /><small>9:41　　　　　　　　　　　　　　　　　●●●</small><h4><i>⌘</i> PocketCode <b>●</b></h4><div className="machine">MacBook Pro <strong>Connected</strong></div><div className="approval"><label>✦　Claude Code <small>Waiting for approval</small></label><h5>Approval required</h5><code>npm install</code><div><button>Reject</button><button>Approve</button></div></div><div className="live">●　<b>Terminal is live</b><small>npm test completed successfully</small></div><footer>⌨　　▱　　⌘　　✦<small>Terminal　 Files　 Git　 Agent</small></footer></div></div></section>
    <section className="strip"><b>Your development environment doesn&apos;t need a browser.</b><p>Keep using VS Code, Cursor, Claude Code, Codex, Git, and your existing local setup. PocketCode simply gives you remote control when you are away from your desk.</p></section>
    <section className="section" id="features"><div className="intro"><Eyebrow>PRODUCT CAPABILITIES</Eyebrow><h2>Everything you need when<br />you&apos;re away from your desk.</h2></div><div className="grid">
      <article className="card terminal-card wide"><div><label>01 / TERMINAL</label><h3>A real terminal.</h3><p>Control the terminal running on your machine, remotely from your phone.</p><small className="pill">Real PTY　 Multiple tabs　 ANSI output</small></div><pre className="term"><span>~/Projects/pocketcodeapk　 main</span>{"\n"}$ git status{"\n"}Changes not staged for commit:{"\n"}<b>modified: extension/src/server.ts</b>{"\n"}$ npm test{"\n"}<strong>PASS　60 tests passed</strong><em>_</em></pre></article>
      <article className="card files"><label>02 / FILES</label><h3>Browse your project.</h3><p>Navigate your project files and inspect or edit them directly from your phone.</p><div className="files-ui">⌄ <b>pocketcodeapk</b><br />　⌄ android/<br />　⌄ docs/<br />　⌄ <b>extension/</b><br />　　 <mark>server.ts</mark><br />　　 protocol.ts<pre><span>export async</span> function{"\n"}connect() &#123;{"\n"}　return socket.open();{"\n"}&#125;</pre></div></article>
      <article className="card git"><label>03 / GIT</label><h3>Git without opening your laptop.</h3><p>Inspect diffs, stage changes, commit, push, pull, and switch branches.</p><div className="git-ui"><b>main</b> <small>3 changed files</small><br /><em>M</em> README.md<br /><em>M</em> extension/src/server.ts<br /><em>M</em> android/app/src/main/...<footer><button>Stage</button><button>Commit</button><button>Push</button></footer></div></article>
      <article className="card agent wide"><div><label>04 / AI AGENTS</label><h3>Your AI coding agent can keep working. <em>You stay in control.</em></h3><p>Monitor agents like Claude Code, Codex, and Aider from your phone. See what they&apos;re doing and respond when they need you.</p></div><div className="agent-ui"><b>✦　Claude Code</b><small>● Running　 Reading: extension/src/server.ts</small><div><label>WAITING FOR APPROVAL</label><code>npm install</code><button>Reject</button><button>Approve</button></div></div></article>
      <article className="card timeline"><label>05 / AGENT TIMELINE</label><h3>See what your agent is actually doing.</h3><p>09:41　Started session<br />09:42　Read package.json<br />09:43　Modified server.ts<br />09:44　Ran tests<br /><b>09:45　Waiting for approval</b></p><strong>$0.83</strong></article>
      <article className="card servers"><label>06 / DEV SERVERS</label><h3>Keep an eye on your dev servers.</h3><p><b>Next.js</b>　localhost:3000　<i>● Running</i><br /><b>API</b>　　 localhost:8080　<i>● Running</i></p><pre>18:23:08 ready - started server{"\n"}<span>GET /api/health 200 14ms</span></pre></article>
      <article className="card snapshot"><label>07 / SNAPSHOTS</label><h3>Take a snapshot before the agent starts.</h3><p>Create a restore point before an AI agent changes your project.</p><div>✓　<b>Snapshot created</b><small>pocketcodeapk · main · 342 files</small><button>Restore</button></div></article></div></section>
    <section className="section demo"><div className="intro"><Eyebrow>THE PRODUCT LOOP</Eyebrow><h2>What happens when you&apos;re<br />away from your desk?</h2></div><div className="steps">{[["STEP 01","You start Claude Code on your computer.","✦ Claude Code","● Running...","Analyzing repository"],["STEP 02","You leave your desk.","⌘　⌁　⌘","encrypted tunnel",""],["STEP 03","The agent needs approval.","APPROVAL REQUIRED","npm install","Approve"],["STEP 04","You approve it. The agent continues.","✦ Claude Code","● Running","✓ Tests passing"]].map(([step,title,line,sub,action]) => <article key={step}><label>{step}</label><h3>{title}</h3><div className={step === "STEP 02" ? "transfer" : ""}>{line}<br /><i>{sub}</i>{action && <><br /><code>{action}</code></>}</div></article>)}</div></section>
    <section className="section stack"><div><Eyebrow>DESIGNED AROUND EXISTING WORKFLOWS</Eyebrow><h2>Works with the tools<br />you already use.</h2></div><div className="tools">{["⌘ VS Code","Cursor","✦ Claude Code","◌ Codex","Aider","⌘ Git","⌁ Tailscale","SSH"].map(tool => <span key={tool}>{tool}</span>)}</div></section>
    <section className="section" id="roadmap"><div className="intro"><Eyebrow>CURRENT STATUS</Eyebrow><h2>Built in public.<br />Shipping incrementally.</h2><p>PocketCode is currently in beta. Some features are already working, while others are actively being built.</p></div><div className="status"><Status title="●　WORKING NOW" items={working} /><Status title="◌　IN DEVELOPMENT" items={future} future /></div></section>
    <section className="beta"><div><Eyebrow>CURRENTLY IN BETA</Eyebrow><h2>Try PocketCode before<br />it leaves beta.</h2><p>PocketCode is open source and actively evolving. Try the current build, see what works, and help shape what gets built next.</p><div className="actions"><CTA>Try the Beta →</CTA><CTA quiet>Star on GitHub</CTA></div><small>Open source · MIT License</small></div></section>
    <section className="section" id="how"><div className="intro"><Eyebrow>THREE STEPS</Eyebrow><h2>Get from your desk<br />to your phone.</h2></div><div className="how">{[["01","⌘","Install","Install the PocketCode Android app and VS Code extension."],["02","▦","Pair","Start a mobile session and scan the generated QR code."],["03","⌨","Control","Use your phone to access your terminal, files, Git, and agent workflows."]].map(([number,icon,title,copy]) => <article key={number}><label>{number}</label><i>{icon}</i><h3>{title}</h3><p>{copy}</p></article>)}</div></section>
    <section className="section security"><div><Eyebrow>SECURITY MODEL</Eyebrow><h2>Your code stays where<br />it belongs.</h2></div><div><p>PocketCode is built around your local development environment. It uses direct connectivity and tunneling options rather than requiring your codebase to live in a hosted cloud IDE.</p><span>Peer-to-peer　 Tailscale　 SSH　 devtunnel</span><a href={repo} target="_blank" rel="noreferrer">Read the security model →</a></div></section>
    <section className="section oss"><div className="repo"><b>⌘　PocketCode</b><small>UnrealAnkit / pocketcodeapk</small><hr />⌘ GitHub　　MIT License　　Public</div><div><Eyebrow>OPEN SOURCE</Eyebrow><h2>Open source.<br />Built in public.</h2><p>The project is public from day one. Look through the code, report an issue, or help shape PocketCode.</p><CTA quiet>View repository</CTA>　<a className="gold" href={repo} target="_blank" rel="noreferrer">Contribute →</a></div></section>
    <section className="section faq"><div><Eyebrow>FAQ</Eyebrow><h2>Useful answers,<br />without the pitch.</h2></div><div>{[["Is PocketCode a cloud IDE?","No. PocketCode remotely controls your existing local development environment."],["Do I need VS Code?","The current workflow uses the PocketCode VS Code extension and supports VS Code, Cursor, or compatible editors."],["Does it work with AI coding agents?","PocketCode is designed to monitor and interact with CLI coding-agent workflows around Claude, Codex, and Aider."],["How does pairing work?","Start a mobile session and scan the generated QR code."],["Is PocketCode open source?","Yes. The repository is public and MIT licensed."]].map(([q,a],i) => <details key={q} open={i === 0}><summary>{q} <b>+</b></summary><p>{a}</p></details>)}</div></section>
  </main><footer className="footer"><a className="brand" href="#top"><i>⌘</i>PocketCode</a><p>Control your code editor from your phone.</p><div><a href={repo}>GitHub</a>　<a href={repo}>Documentation</a>　<a href={repo}>Security</a>　<a href={repo}>License</a></div><small>Currently in beta.</small></footer></>;
}

function Status({ title, items, future = false }) {
  return <article className={future ? "future" : ""}><label>{title}</label><ul>{items.map(([name,copy]) => <li key={name}><b>{name}</b><span>{copy}</span></li>)}</ul>{future && <small>No artificial dates. Just what we&apos;re building next.</small>}</article>;
}
